CREATE TABLE IF NOT EXISTS "things" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "things_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"thing" text NOT NULL
);
